### ISSUE TITLE
NPE and string conversion errors when converting from GoMule Atma stash 0.43 to 0.44

### ISSUE THREAD

**Issue by mihaeu** [pairofdocs/atma-stash-d2r#2]
Hi and thank you so much for all the effort you put into this project. If there's anyway to donate a coffee, I'd gladly do that 🙏 ☕ 

I started muling my most important things over using new characters, but with all my stuff this obviously takes hours. I used GoMule 0.42 and 0.43 (same issue) for creating and managing the Atma stashes. My D2R stuff is on GoMule 0.44 the most recent version.

When I converted my main stash file, I always get errors. I made sure the stash contains no duplicate items or any other obvious problems. I tried deleting the files in question, but couldn't really make out what the common denominator would be and how many more of those items there'd be.

I'll attach the stack traces I got when loading the converted file 
[stacktraces.log](https://github.com/pairofdocs/atma-stash-d2r/files/7835116/stacktraces.log)
[LoD_created_withGomule0.43.zip](https://github.com/pairofdocs/atma-stash-d2r/files/7835120/LoD_created_withGomule0.43.zip)
and my stash file in case you have a few minutes to look at them, but here's an excerpt:

```
Error

Error: For input string: "" (Small Charm of Vita, 0x5898c6b8)
	at gomule.item.D2Item.<init>(D2Item.java:174)
	at gomule.d2x.D2Stash.readItems(D2Stash.java:183)
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:151)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
```

and 

```
Error: null (Azure Small Charm of Vita, 0xdce53df6)
	at gomule.item.D2Item.<init>(D2Item.java:174)
	at gomule.d2x.D2Stash.readItems(D2Stash.java:183)
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:151)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
	at gomule.gui.D2FileManager.addItemList(D2FileManager.java:1618)
```

and 

```
Error

Error: null (Peasant Crown, 0xc2a6091e)
	at gomule.item.D2Item.<init>(D2Item.java:174)
	at gomule.d2x.D2Stash.readItems(D2Stash.java:183)
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:151)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
	at gomule.gui.D2FileManager.addItemList(D2FileManager.java:1618)
	at gomule.gui.D2ViewStash.connect(D2ViewStash.java:352)
```

Any help would be appreciated, but I know how it is and sometimes open source becomes overwhelming 😁 anyway, have a lovely rest of your weekend 👋 

UPDATE: I logged the version to be sure and it's 96. There are no errors in the developer console of Chrome 🤔

**Comment by pairofdocs** [comment]
Hi,
Thanks for including logs and details.

Try using this converter https://pairofdocs.github.io/atma-stash-d2r/convert96to97.html

That one is for converting Atma stashes to stashes in Gomule from Silos (https://sourceforge.net/projects/gomule/files/gomule/R0.44/GoMuleR4.4.13_Resurrected_1.0.zip/download?use_mirror=versaweb&download=&failedmirror=newcontinuum.dl.sourceforge.net)

(the other converter, https://pairofdocs.github.io/atma-stash-d2r/ , is for converting atma stashes to my old version of Gomule-d2r on github, https://github.com/pairofdocs/gomule-d2r , which was a fork of Silos' Gomule LoD version)

**Comment by mihaeu** [comment]
Thanks for getting back to me. I used the correct converter, but I found the solution to my problem in the original repository: I had to split up the file into smaller ones of about 1000 items and it worked.

Shall we add a warning to the html file? Would you accept a PR for that?

**Comment by pairofdocs** [comment]
Ah, good find.

Sure we can add a warning for that. I'll merge in your PR
